swagger: "2.0"
info:
  description: "This API is a simple CRUD of recipes."
  version: "1.0.0"
  title: "Ogre's Recipes"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "petstore.swagger.io"
# basePath: "/v2"
tags:
- name: "recipe"
  description: "Food recipes"
schemes:
- "http"
paths:
  /recipe:
    post:
      tags:
      - "recipe"
      summary: "Add a new recipe"
      description: ""
      operationId: "addRecipe"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Recipe object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Recipe"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Recipe"
        "405":
          description: "Invalid input"
    get:
      tags:
      - "recipe"
      summary: "Return all saved recipes"
      operationId: "listRecipes"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema: 
            $ref: "#/definitions/ListRecipes"
  #/pet/findByTags:
  /recipe/{recipeId}:
    get:
      tags:
      - "recipe"
      summary: "Find recipe by ID"
      description: "Returns a single recipe"
      operationId: "getRecipeById"
      produces:
      - "application/json"
      parameters:
      - name: "recipeId"
        in: "path"
        description: "ID of recipe to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Recipe"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Recipe not found"
    delete:
      tags:
      - "recipe"
      summary: "Deletes a recipe"
      description: ""
      operationId: "deleteRecipe"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "recipeId"
        in: "path"
        description: "Recipe id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
  /recipe/{recipeId}/uploadImage:
    post:
      tags:
      - "recipe"
      summary: "Uploads an image"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "recipeId"
        in: "path"
        description: "ID of recipe to update"
        required: true
        type: "integer"
        format: "int64"
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: true
        type: "file"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  Recipe:
    type: "object"
    required:
    - "title"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "Lasagna"
      description:
        type: "string"
      ingredients:
        type: "string"
      howToDo:
        type: "string"
      imgUrl:
        type: "string"
      timeToCook:
        type: "string"
  ListRecipes:
    type: "array"
    items:
      $ref: "#/definitions/Recipe"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"